services:
  kafka:
    image: docker.io/bitnamilegacy/kafka:3.8.1
    ports:
      - 9092:9092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  redpanda:
    image: docker.io/redpandadata/console:v2.7.2
    ports:
      - 7071:7071
    restart: always
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKERS=kafka:9094
      - SERVER_LISTENPORT=7071
  pubsub:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    ports:
      - 6379:6379
  #############################
  # Monitoring
  #############################
  prometheus:
    image: prom/prometheus:latest
    # ports:
    #   - "9090:9090"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    restart: always
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana:/etc/grafana/provisioning
    restart: always
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
  kminion:
    image: redpandadata/kminion:v2.2.14
    restart: always
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKERS=kafka:9094
